---
# https://dprint.dev/install/
- name: Download Atuin installer
  ansible.builtin.get_url:
    url: https://setup.atuin.sh
    dest: /tmp/atuin_install.sh
    mode: "0755"

- name: Install Atuin (and import previous shell history)
  ansible.builtin.shell: /tmp/atuin_install.sh && ~/.atuin/bin/atuin import auto
  args:
    creates: ~/.atuin/bin

- name: Update Atuin bash startup script to disable up-arrow binding
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    regexp: "\\$\\(atuin init bash\\)"
    line: 'eval "$(atuin init bash --disable-up-arrow)"'
    backrefs: true

- name: Upgrade Atuin
  ansible.builtin.command: ~/.atuin/bin/atuin-update
  register: atuin_upgrade
  changed_when: "'Already up to date' not in atuin_upgrade.stderr"
