---
# https://dprint.dev/install/
- name: Install Dprint
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://dprint.dev/install.sh | sh
  args:
    creates: ~/.dprint/bin/dprint

- name: Upgrade dprint
  ansible.builtin.command: dprint upgrade
  register: dprint_upgrade
  changed_when: "'Already on latest version' not in dprint_upgrade.stdout"
