---
# https://dprint.dev/install/
- name: Download Dprint installer
  ansible.builtin.get_url:
    url: https://dprint.dev/install.sh
    dest: /tmp/dprint_install.sh
    mode: "0755"

- name: Install Dprint
  ansible.builtin.command: /tmp/dprint_install.sh
  args:
    creates: ~/.dprint/bin/dprint

- name: Upgrade dprint
  ansible.builtin.command: dprint upgrade
  register: dprint_upgrade
  changed_when: "'Already on latest version' not in dprint_upgrade.stdout"
