---
# We only ensure it is installed because the tool automatically update himself afterward.
# https://www.jetbrains.com/help/rust/installation-guide.html#-nhkivi_92
- name: Check if JetBrains Toolbox is installed
  ansible.builtin.stat:
    path: ~/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox
  register: thibaut_jetbrains_toolbox

- name: Download and install JetBrains ToolBox
  when: not thibaut_jetbrains_toolbox.stat.exists
  block:
    - name: Create JetBrains ToolBox download dir
      ansible.builtin.file:
        path: /tmp/jetbrains-toolbox
        state: directory
        mode: "0755"

    # This url redirects to the latest release, whose top dir embeds the version.
    - name: Download JetBrains ToolBox
      ansible.builtin.unarchive:
        src: https://data.services.jetbrains.com/products/download?platform=linux&code=TBA
        dest: /tmp/jetbrains-toolbox
        remote_src: true
        extra_opts: [--strip-components=1]

    - name: Launch JetBrains ToolBox
      ansible.builtin.command: /tmp/jetbrains-toolbox/bin/jetbrains-toolbox
      changed_when: true
