---
# Jetbrains Toolbox does not provide a 'latest' url so we have to manually find it.
# We only ensure it is installed because the tool automatically update himself afterward.
# https://www.jetbrains.com/help/rust/installation-guide.html#-nhkivi_92
- name: Check if JetBrains Toolbox is installed
  ansible.builtin.stat:
    path: ~/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox
  register: jetbrains_toolbox_installed
  ignore_errors: true
  changed_when: false

- name: Download and install JetBrains ToolBox
  when: not jetbrains_toolbox_installed.stat.exists
  block:
    - name: Ensure libfuse2 is installed (Toolbox requirement)
      ansible.builtin.apt:
        name:
          - libfuse2
        state: present
      become: true

    - name: Get latest Jetbrains Toolbox download page
      ansible.builtin.uri:
        url: https://www.jetbrains.com/toolbox-app/download/download-thanks.html?platform=linux
        return_content: true
      register: jetbrains_download_page

    - name: Find all versions of JetBrains Toolbox
      ansible.builtin.uri:
        url: https://data.services.jetbrains.com/products/releases?code=TBA&type=release
        return_content: true
      register: jetbrains_index
      check_mode: false

    - name: Finds the latest version of JetBrains Toolbox
      ansible.builtin.set_fact:
        jetbrains_toolbox_version: "{{ (jetbrains_index.content | from_json).TBA.0.build }}"

    - name: Download JetBrains ToolBox
      ansible.builtin.unarchive:
        src: https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz
        dest: /tmp
        remote_src: true

    - name: Launch JetBrains ToolBox
      ansible.builtin.command: /tmp/jetbrains-toolbox-{{ jetbrains_toolbox_version }}/jetbrains-toolbox
      changed_when: true
