---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_schedule: monthly
  skip:
    - dprint-fmt
    - ansible-lint

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/ansible/ansible-lint
    rev: 262624cd0ab22a4221293216856c59671ce7aa5e  # frozen: v26.6.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/trim21/dprint-pre-commit
    rev: 157f9067861f534fe04c49c81a2cc48f4944f6fa  # frozen: v0.55.1.4
    hooks:
      - id: dprint
