---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_schedule: monthly
  skip:
    - dprint
    - ansible-lint

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/ansible/ansible-lint
    rev: 665d9e07a1943254d2910faffc106adaf7ea7294  # frozen: v26.8.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/trim21/dprint-pre-commit
    rev: cc6b2a6b05f510cfe72ef4e8f14c7a0422c81404  # frozen: v0.57.4.0
    hooks:
      - id: dprint
