---
- name: Sanity checks
  hosts: localhost
  connection: local
  any_errors_fatal: true
  tasks:
    - name: Check we are running in the directory of the script
      failed_when: not ansible_env.PWD.endswith('/ubuntu-dev-ansible')
      ansible.builtin.debug:
        msg: This playbook should only be run from the `ubuntu-dev-ansible` folder
    - name: Validate become password is valid
      become: true
      ansible.builtin.command: whoami
      changed_when: false
      timeout: 1

- name: Setup ubuntu machine
  hosts: localhost
  connection: local
  roles:
    - thibaut
