---
# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
- name: Download awscliv2 installer
  ansible.builtin.unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip
    dest: /tmp
    remote_src: true
    creates: /tmp/aws
    mode: "0755"

- name: Run the awscliv2 installer
  ansible.builtin.command:
    cmd: /tmp/aws/install --update
  become: true
  register: aws_install
  changed_when: "'Skipping install' not in aws_install.stdout"
