---
- name: Dotfiles dirs
  ansible.builtin.file:
    path: ~/.{{ item }}
    state: directory
    mode: "0755"
  loop:
    - ipython/profile_default/startup
    - config/dust
    - aws

- name: Create Dotfiles
  ansible.builtin.copy:
    src: "{{ thibaut_files }}/dotfiles/{{ item }}"
    dest: ~/.{{ item }}
    mode: "0755"
    force: false
  loop:
    - aws/config
    - config/dust/config.toml
    - config/ripgreprc
    - ipython/profile_default/startup/00-imports.py
    - ansible.cfg
    - bash_aliases
    - digrc
    - gitconfig_opensource
    - gitignore

- name: Update ~/.bashrc for various tools
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    create: true
    mode: "0644"
    block: |
      eval "$(fzf --bash)"
      export DPRINT_INSTALL="$HOME/.dprint"
      export N_PREFIX=$HOME/.n
      export PATH="$HOME/.atuin/bin:$N_PREFIX/bin:$DPRINT_INSTALL/bin:$PATH"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: tools"
    prepend_newline: true
    append_newline: true
