---
- name: Change GRUB timeout from 0 to -1
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    search_string: "GRUB_TIMEOUT"
    line: "GRUB_TIMEOUT=-1"
    state: present
  become: true
  register: grub_config_changed

- name: Update generated grub file # noqa: no-handler
  ansible.builtin.command: update-grub
  become: true
  when: grub_config_changed.changed
  changed_when: true
