# Posix
alias restart="source ~/.bashrc"
alias perms="stat -c '%a - %n'"

# interactive modes
alias cp="cp -i"
alias ln="ln -i"
alias mv="mv -i"

# Python & friends
alias python=python3
alias pm='python manage.py'
alias pr="pre-commit run"
function workon() { source ~/.virtualenvs/$1/bin/activate; }

# Rust
alias cwr="cargo watch -q -c -x 'run -q'"

# Clipboard utils
alias clip="xclip -selection c"

# Kill stopped processes
alias kstop="kill -9 $(jobs -p)"

# ripgrep
alias rgm='rg --no-filename --only-matching --no-line-number'

# rip
alias rip='rip --graveyard ~/.local/share/Trash/files'

# Git
alias grgc="git reset --hard HEAD && git clean -fd"
alias rmgm='git branch --merged master | grep -v master | xargs git branch -d'

alias gc="git commit -m"
alias gca="git commit -am"
alias gcf="git commit --amend --reuse-message HEAD"

alias gl="git log --oneline --decorate --graph"
alias glog="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gls="git log --stat"

alias gps="git push"
alias gpl="git pull"
alias gs="git status -s -b"

# https://adamj.eu/tech/2025/05/08/docker-disable-adverts/
export DOCKER_CLI_HINTS=false