---
- name: Check if ~/workspace exists
  ansible.builtin.stat:
    path: ~/workspace
  register: workspace_stat

- name: Create ~/workspace if it doesn't exist
  ansible.builtin.file:
    path: ~/workspace
    state: directory
    mode: "0755"
  when: not workspace_stat.stat.exists

- name: Check all-repos config drift
  ansible.builtin.command:
    cmd: diff "{{ thibaut_files }}/{{ item }}" "~/{{ item }}"
  register: all_repos_conf_diff
  changed_when: all_repos_conf_diff.rc >= 1
  ignore_errors: true
  loop:
    - all-repos.json
    - my-repos.json

- name: Clone all missing repos # noqa: no-handler
  when: all_repos_conf_diff.changed
  block:
    - name: Update all-repos config files
      ansible.builtin.copy:
        src: "{{ thibaut_files }}/{{ item }}"
        dest: ~/{{ item }}
        mode: "0600"
        force: true
      loop:
        - all-repos.json
        - my-repos.json

    - name: Run all-repos-clone command
      ansible.builtin.command:
        cmd: all-repos-clone --jobs -1
        chdir: "{{ ansible_env.HOME }}"
      changed_when: true

    - name: Get list of git repos in /tmp/workspace
      ansible.builtin.find:
        paths: /tmp/workspace
        file_type: directory
      register: tmp_git_repos

    - name: Check which git repo don't exist in ~/workspace
      ansible.builtin.stat:
        path: ~/workspace/{{ item.path | basename }}
      loop: "{{ tmp_git_repos.files }}"
      register: workspace_dir_stats

    - name: Copy missing git repos to ~/workspace
      ansible.builtin.copy:
        src: "{{ item.item.path }}/"
        dest: ~/workspace/{{ item.item.path | basename }}/
        remote_src: true
        mode: preserve
      loop: "{{ workspace_dir_stats.results }}"
      when: not item.stat.exists
