---
- name: Ensure apt-transport-https is installed (for https signing urls)
  ansible.builtin.apt:
    name:
      - apt-transport-https
    state: present

- name: Add google APT repository
  ansible.builtin.deb822_repository:
    name: google
    types: [deb]
    uris:
      - http://dl.google.com/linux/chrome/deb
    signed_by: https://dl.google.com/linux/linux_signing_key.pub
    suites: [stable]
    components: [main]
    architectures: amd64
    enabled: true

- name: Add Docker APT repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris:
      - https://download.docker.com/linux/ubuntu
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    suites: "{{ ansible_distribution_release }}" # noble, focal, ...
    components: [stable]
    architectures: amd64
    enabled: true

- name: Add Mozilla APT repository
  ansible.builtin.deb822_repository:
    name: mozilla
    types: [deb]
    uris:
      - https://packages.mozilla.org/apt
    signed_by: https://packages.mozilla.org/apt/repo-signing-key.gpg
    suites: [mozilla]
    components: [main]
    architectures: amd64
    enabled: true

- name: Add Spotify APT repository
  ansible.builtin.deb822_repository:
    name: spotify
    types: [deb]
    uris:
      - http://repository.spotify.com
    signed_by: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
    suites: [stable]
    components: [non-free]
    architectures: amd64
    enabled: true

- name: Add TablePlus APT repository
  ansible.builtin.deb822_repository:
    name: tableplus
    types: [deb]
    uris:
      - https://deb.tableplus.com/debian/24
    signed_by: https://deb.tableplus.com/apt.tableplus.com.gpg.key
    suites: [tableplus]
    components: [main]
    architectures: amd64
    enabled: true

- name: Add Visual Studio Code APT repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris:
      - https://packages.microsoft.com/repos/code
    signed_by: /etc/apt/keyrings/packages.microsoft.gpg
    suites: [stable]
    components: [main]
    architectures: amd64
    enabled: true

- name: Add Foliate PPA repository
  ansible.builtin.apt_repository:
    repo: ppa:apandada1/foliate
