---
- name: Ensure apt-transport-https is installed (for https signing urls)
  ansible.builtin.apt:
    name:
      - apt-transport-https
    state: present

- name: Set architecture to amd64 if x86_64
  ansible.builtin.set_fact:
    architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

- name: Add google APT repository
  ansible.builtin.deb822_repository:
    name: google
    types: [deb]
    architectures: "{{ architecture }}"
    uris: http://dl.google.com/linux/chrome/deb
    signed_by: https://dl.google.com/linux/linux_signing_key.pub
    suites: [stable]
    components: [main]
    enabled: true

- name: Add Docker APT repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    architectures: "{{ architecture }}"
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"] # noble, focal, ...
    components: [stable]
    enabled: true

- name: Add Mozilla APT repository
  ansible.builtin.deb822_repository:
    name: mozilla
    types: [deb]
    architectures: "{{ architecture }}"
    uris: https://packages.mozilla.org/apt
    signed_by: https://packages.mozilla.org/apt/repo-signing-key.gpg
    suites: [mozilla]
    components: [main]
    enabled: true

- name: Add Spotify APT repository
  ansible.builtin.deb822_repository:
    name: spotify
    types: [deb]
    architectures: "{{ architecture }}"
    uris: http://repository.spotify.com
    signed_by: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
    suites: [stable]
    components: [non-free]
    enabled: true

- name: Add TablePlus APT repository
  ansible.builtin.deb822_repository:
    name: tableplus
    types: [deb]
    architectures: "{{ architecture }}"
    uris: "https://deb.tableplus.com/debian/{{ ansible_distribution_major_version }}"
    signed_by: https://deb.tableplus.com/apt.tableplus.com.gpg.key
    suites: [tableplus]
    components: [main]
    enabled: true

- name: Add Visual Studio Code APT repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    architectures: "{{ architecture }}"
    uris: https://packages.microsoft.com/repos/code
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    suites: [stable]
    components: [main]
    enabled: true

- name: Add Tailscale APT repository
  ansible.builtin.deb822_repository:
    name: tailscale
    types: [deb]
    architectures: "{{ architecture }}"
    uris: "https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}"
    signed_by: "https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.noarmor.gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [main]
    enabled: true

- name: Add caprine APT repository
  ansible.builtin.deb822_repository:
    name: caprine
    types: [deb]
    uris: "https://apt.fury.io/lefterisgar/"
    suites: ["*"]
    components: ["*"]
    enabled: true
    trusted: true

- name: Set MongoDB version based on Ubuntu release
  ansible.builtin.set_fact:
    mongodb_version: "{{ '8.0' if ansible_distribution_release == 'noble' else '7.0' }}"

- name: Add MongoDB APT repository based on Ubuntu release
  ansible.builtin.deb822_repository:
    name: "mongodb-org-{{ mongodb_version }}"
    types: [deb]
    architectures: "{{ architecture }}"
    uris: "https://repo.mongodb.org/apt/{{ ansible_distribution | lower }}"
    signed_by: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    suites:
      - "{{ ansible_distribution_release | lower }}/mongodb-org/{{ mongodb_version }}"
    components: [multiverse]
    enabled: true
  when: ansible_distribution_release in ['noble', 'jammy']

- name: Add Foliate PPA repository
  ansible.builtin.apt_repository:
    repo: ppa:apandada1/foliate
