---
- name: Setup apt repositories & Update apt cache
  ansible.builtin.import_tasks: apt_repositories.yml
  become: true

- name: Install apt packages # noqa: package-latest
  ansible.builtin.apt:
    name: "{{ thibaut_apt_packages }}"
    state: latest
  become: true

- name: Upgrade apt packages
  ansible.builtin.apt:
    upgrade: safe
  become: true

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true
  become: true
  tags:
    - cleanup

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
  become: true
  tags:
    - cleanup

- name: Download .deb packages from url
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: /tmp/{{ item.file_name }}
    timeout: 30
    mode: "0755"
  loop: "{{ thibaut_deb_packages }}"

- name: Install downloaded .deb packages
  ansible.builtin.apt:
    deb: /tmp/{{ item.file_name }}
  loop: "{{ thibaut_deb_packages }}"
  become: true

- name: Install slack latest .deb package
  ansible.builtin.import_tasks: packages/slack.yml

- name: Install MongoDB Compass
  ansible.builtin.import_tasks: packages/mongodb-compass.yml

# Fix an issue with Ubuntu 24.04 about the unprivileged namespaces,
# See https://docs.docker.com/desktop/install/linux/ubuntu/#prerequisites
- name: Fix Docker Desktop startup on 24.04
  ansible.posix.sysctl:
    name: kernel.apparmor_restrict_unprivileged_userns
    value: "0"
    sysctl_set: true
  become: true

# Fix an issue with gitkraken adding a weird shortcut file making the
# favorite bar not working properly
- name: Remove gitkraken-url-handler.desktop
  ansible.builtin.file:
    path: /usr/share/applications/gitkraken-url-handler.desktop
    state: absent
  become: true