---
- name: Setup fzf shell integration
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    create: true
    mode: "0644"
    block: |
      eval "$(fzf --bash)"
      export DPRINT_INSTALL="$HOME/.dprint"
      export N_PREFIX=$HOME/.n
      export PATH="$N_PREFIX/bin:$DPRINT_INSTALL/bin:$PATH"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: tools"
    prepend_newline: true
    append_newline: true
