---
- name: Setup fzf shell integration
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    create: true
    mode: "0644"
    block: |
      eval "$(fzf --bash)"
      export DPRINT_INSTALL="/home/thibaut/.dprint"
      export PATH="$DPRINT_INSTALL/bin:$PATH"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: tools"
    prepend_newline: true
    append_newline: true
