---
- name: Dotfiles dirs
  ansible.builtin.file:
    path: ~/.{{ item }}
    state: directory
    mode: "0755"
  loop:
    - ipython/profile_default/startup
    - config/dust
    - aws
  tags:
    - dotfiles

- name: Create Dotfiles
  ansible.builtin.copy:
    src: "{{ thibaut_files }}/dotfiles/{{ item }}"
    dest: ~/.{{ item }}
    mode: "0755"
    force: false
  loop:
    - aws/config
    - config/dust/config.toml
    - config/ripgreprc
    - ipython/profile_default/startup/00-imports.py
    - ansible.cfg
    - digrc
    - gitconfig_opensource
    - gitignore
  tags:
    - dotfiles
