---
- name: Update apt package manager cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags:
    - apt

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ thibaut_apt_packages }}"
    state: latest
  become: true
  tags:
    - apt

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true
  become: true
  tags:
    - apt
    - cleanup

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
  become: true
  tags:
    - apt
    - cleanup
