---
- name: Basic SSH settings
  ansible.builtin.import_tasks: system/ssh.yml
  tags:
    - ssh

- name: Customize grub dual boot
  ansible.builtin.import_tasks: system/grub.yml
  tags:
    - grub

- name: Copy dotfiles
  ansible.builtin.import_tasks: system/dotfiles.yml
  tags:
    - dotfiles

- name: Install tools via apt/brew/uv/cargo
  ansible.builtin.import_tasks: installs.yml
  tags:
    - installs

- name: Add some symlinks
  ansible.builtin.import_tasks: system/symlinks.yml
  tags:
    - symlinks

- name: Load GNOME dconf settings
  ansible.builtin.import_tasks: system/gnome.yml
  tags:
    - gnome

- name: Clone my repos into ~/workspace
  ansible.builtin.import_tasks: all-repos.yml
  tags:
    - all-repos

- name: Self hosted LLM (Require `--tags llm` to be executed)
  ansible.builtin.import_tasks: llm.yml
  tags:
    - llm
    - never
