---
- name: Basic SSH settings
  ansible.builtin.import_tasks: ssh.yml

- name: Install tools via apt/brew/uv/cargo
  ansible.builtin.import_tasks: installs.yml

- name: Copy dotfiles
  ansible.builtin.import_tasks: dotfiles.yml
  tags:
    - dotfiles

- name: Add some symlinks
  ansible.builtin.import_tasks: symlinks.yml

- name: Load GNOME dconf settings
  ansible.builtin.import_tasks: gnome.yml
  tags:
    - gnome

- name: Clone my repos into ~/workspace
  ansible.builtin.import_tasks: all-repos.yml
  tags:
    - all-repos
