---
- name: Basic settings
  ansible.builtin.import_tasks: ssh.yml

- name: Setup apt
  ansible.builtin.import_tasks: apt.yml
  become: true

- name: Install things
  ansible.builtin.import_tasks: installs.yml

- name: Link in dotfiles
  ansible.builtin.import_tasks: dotfiles.yml
  tags:
    - dotfiles

- name: Update bash related files
  ansible.builtin.import_tasks: bash.yml
  tags:
    - bash

- name: Add some symlinks
  ansible.builtin.import_tasks: symlinks.yml

- name: Clone my repos into ~/workspace
  ansible.builtin.import_tasks: all-repos.yml
  tags:
    - all-repos
