---
- name: Basic settings
  ansible.builtin.import_tasks: ssh.yml

- name: Setup apt
  ansible.builtin.import_tasks: apt.yml
  become: true

- name: Install things
  ansible.builtin.import_tasks: installs.yml

- name: Update bash related files
  ansible.builtin.import_tasks: bash.yml

- name: Add some symlinks
  ansible.builtin.import_tasks: symlinks.yml

