---
thibaut_apt_packages:
  - curl
  - git
  - google-chrome-stable
  - hyperfine
  - nginx
  - jq
  - sd
  - tmux
  - tree
  - wget
  # Build tools
  - pkg-config
  - default-libmysqlclient-dev
  - gcc
  - build-essential
  # Geolibraries
  - binutils
  - libproj-dev
  - gdal-bin
  # GUI
  - foliate # Ebook reader
# Use brew for packages that are lagging a lot behind in apt.
thibaut_brew_packages:
  - btop
  - fd
  - fzf
  - tlrc
  - ripgrep
  - pandoc

# thibaut_homebrew_cask_packages:
#   - discord
#   - docker
#   - evernote
#   - firefox
#   - font-ubuntu-mono-nerd-font
#   - google-earth-pro
#   - istat-menus
#   - karabiner-elements
#   - keyboard-maestro
#   - mactex
#   - rectangle
#   - steam
#   - tableplus
#   - vlc

#  - awscli ~# TODO: v2 is a shitshow top install
# TODO: https://github.com/asottile/all-repos
# Try: starship - detailed terminal prompt
thibaut_uv_tools:
  - name: black
  - name: ruff
  - name: httpie
  - name: ipython
  - name: hatch
  - name: twine
  - name: build
  - name: auditwheel
  - name: yt-dlp
  - name: ebcli
  - name: jpegoptim-py
  - name: shellcheck-py
  - name: pre-commit
    with:
      - pre-commit-uv # Really not sure about that
  - name: tox
    with:
      - tox-uv

thibaut_cargo_tools:
  - tokei
