---
thibaut_apt_packages:
  - curl
  - firefox-nightly
  - git
  - google-chrome-stable
  - hyperfine
  - nginx
  - jq
  - sd
  - tmux
  - tree
  - wget
  # Build tools
  - pkg-config
  - default-libmysqlclient-dev
  - gcc
  - build-essential
  # Geolibraries
  - binutils
  - libproj-dev
  - gdal-bin
  # GUI
  - foliate # Ebook reader
  - spotify-client

thibaut_deb_packages:
  - url: https://discord.com/api/download?platform=linux&format=deb
    file_name: discord-latest.deb
  - url: https://desktop.docker.com/linux/main/amd64/docker-desktop-amd64.deb
    file_name: docker-desktop-amd64.deb
  - url: https://release.gitkraken.com/linux/gitkraken-amd64.deb
    file_name: gitkraken-amd64.deb

# Use brew for packages that are lagging a lot behind in apt.
thibaut_brew_packages:
  - btop
  - fd
  - fzf
  - tlrc
  - ripgrep
  - pandoc

# thibaut_homebrew_cask_packages:
#   - tableplus
#   - vlc

#  - awscli ~# TODO: v2 is a shitshow top install
# TODO: https://github.com/asottile/all-repos
# Try: starship - detailed terminal prompt
thibaut_uv_tools:
  - name: black
  - name: ruff
  - name: httpie
  - name: ipython
  - name: hatch
  - name: twine
  - name: build
  - name: auditwheel
  - name: yt-dlp
  - name: ebcli
  - name: jpegoptim-py
  - name: shellcheck-py
  - name: pre-commit
    with:
      - pre-commit-uv # Really not sure about that
  - name: tox
    with:
      - tox-uv

thibaut_cargo_tools:
  - tokei
